### ISSUE TITLE
Create Event component

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/hlg-website#14]
<img width="380" alt="image" src="https://github.com/acm-ucr/hlg-website/assets/90938120/54dabe81-3af6-41ab-81c6-2acdaa97bb77">

* Static info is okay for now

src/components/events/Event.jsx

**Comment by Lanceart** [comment]
Hi, I finished this part.
![image](https://github.com/acm-ucr/hlg-website/assets/62589604/54dc6c5c-8ba4-4f78-84b3-2d5ad527596c)

**Comment by Lanceart** [comment]
you can use this like the following code.
![image](https://github.com/acm-ucr/hlg-website/assets/62589604/e696efcf-d857-4333-8ea3-658bf0c33af1)
And the result is this:
![image](https://github.com/acm-ucr/hlg-website/assets/62589604/d18571e8-4dbf-41b7-b321-744108e1ba88)
