### ISSUE TITLE
Make calendar component

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/hlg-website#35]
<img width="538" alt="image" src="https://github.com/acm-ucr/hlg-website/assets/90938120/d53fa659-6df2-4e45-a9be-cc74159985d7">

* we don't have any events yet so you can make everything static for now 
* you can reference this https://github.com/acm-ucr/asme-website/blob/dev/src/components/events/Calendar.jsx

src/components/Calendar.jsx

**Comment by Lanceart** [comment]
![image](https://github.com/acm-ucr/hlg-website/assets/62589604/61b39f19-1481-4b99-9daf-27a3971d40d0)

One bugs one optimize.
1. When init the color in each items not works.
2. the css file should be embedded into the jsx file.
