### ISSUE TITLE
Set up staff page

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/hlg-website#61]
<img width="1280" alt="image" src="https://github.com/acm-ucr/hlg-website/assets/90938120/7cd1771c-1532-490a-8b5f-553e16bd62c1">
<img width="1280" alt="image" src="https://github.com/acm-ucr/hlg-website/assets/90938120/cd2005f2-2f5f-4bc4-814e-2ffe3b5b9403">

1. include all of these headings using \<Heading/\> on the page
2. create an array of dummy 4 staff member objects with a name, discord, email, position, and image fields (they can all be the same)
3. map through the 4 objects 4 times using \<Staff /\> component (once for exec board, once for esports, once for media, once for events)

src/app/staff/page.js

**Comment by JohnZ9865** [comment]
![image](https://github.com/acm-ucr/hlg-website/assets/64669569/da2c3fc5-6355-457c-a069-9535baa50bae)
Not sure if the staff part is too big.
