### ISSUE TITLE
Fix mobile responsiveness for Intro.jsx

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/hlg-website#62]
<img width="205" alt="image" src="https://github.com/acm-ucr/hlg-website/assets/90938120/3ce25c7f-ebae-4d1e-813e-b6120560fded">

use breakpoints to make these objects centered and flex-col on top of each other nicely in this order
1. WHO WE ARE on top
2. image
3. Founded in ...
4. Through Highlander Gaming... on bottom

src/components/home/Intro.jsx

**Comment by Lanceart** [comment]
![image](https://github.com/acm-ucr/hlg-website/assets/62589604/3ba8e865-acc6-4dbe-baf1-c03ae9af40be)
![image](https://github.com/acm-ucr/hlg-website/assets/62589604/fb8ba4b0-3617-4de2-bc11-22293b2ad2eb)

**Comment by Lanceart** [comment]
Fixed the format error in the mobile screen space.
