### ISSUE TITLE
Mobile responsiveness of Staff page

### ISSUE THREAD

**Issue by pondohoo** [acm-ucr/hlg-website#72]
<img width="205" alt="image" src="https://github.com/acm-ucr/hlg-website/assets/90938120/1826a5ea-f782-49fe-bbe0-7fc2382102a4">

* add breakpoints to tailwind styles so there are 2 <Staff/> objects per row instead of 4 in mobile 

src/app/staff/page.js

**Comment by Lanceart** [comment]
I finished this task, please check it.
Normal screen space.
![image](https://github.com/acm-ucr/hlg-website/assets/62589604/c2d31a66-2b88-4037-ae26-ab6d46fc7be2)
Mobile screen space
![image](https://github.com/acm-ucr/hlg-website/assets/62589604/7be60558-69ec-4982-b897-f820afbf9668)
